default: all
Q0 : Q0.c
	gcc -Wall -std=c99 -o Q0 Q0.c
Q1 : Q1.c
	gcc -Wall -std=c99 -o Q1 Q1.c
Q2 : Q2.c
	gcc -Wall -std=c99 -o Q2 Q2.c
Q3 : Q3.c
	gcc -Wall -std=c99 -o Q3 Q3.c

clean:
	rm	Q0 Q1 Q2 Q3

all:
	gcc -Wall -std=c99 -o Q0 Q0.c
	gcc -Wall -std=c99 -o Q1 Q1.c
	gcc -Wall -std=c99 -o Q2 Q2.c
	gcc -Wall -std=c99 -o Q3 Q3.c
	

